#!/usr/bin/env python3
"""Restartable V49 current-source continuation with an explicit load origin."""

from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import subprocess
import time

import numpy as np

from full_model.analysis.run_v34_finite_coupled_response import (
    I3Controls, _energy_options, resolved_bicrystal, run_i3_cycle,
)
from full_model.analysis.run_v39_common_horizon import (
    atomic_json, load_stage, save_stage,
)
from full_model.analysis.run_v48_physical_continuation import (
    energy, load_record, observables,
)


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def driving(grid, initial_tensor_shear, protocol, rate_s, load_time_s):
    shear = float(initial_tensor_shear)
    if protocol == "continued_deformation":
        shear += float(rate_s)*float(load_time_s)
    from full_model.production.common_tensorial_wall import CommonWallDriving
    return CommonWallDriving(
        mean_strain=np.asarray(((0.0, shear), (shear, 0.0))),
        fixed_eigenstrain=np.zeros((grid, grid, 2, 2)))


def advance_consistent_midpoint_segment(
        context, state, *, grid, initial_tensor_shear, protocol, rate,
        physical_time, load_origin, requested_duration,
        maximum_duration_retries=16, cycle_runner=run_i3_cycle,
        energy_evaluator=energy):
    """Select a duration and rerun until its generating midpoint is exact.

    A shortened candidate is a numerical probe only. It is discarded and the
    same immutable pretrial state is rerun using the shortened duration and its
    corresponding midpoint load. Nothing returned to the caller is published
    until the duration used to build the load agrees with the accepted clock.
    """
    original = state
    selected = float(requested_duration)
    if selected <= 0.0 or not np.isfinite(selected):
        raise ValueError("requested segment duration must be positive")
    attempts = []
    for retry in range(int(maximum_duration_retries)+1):
        midpoint_time = physical_time+.5*selected
        midpoint_drive = driving(
            grid, initial_tensor_shear, protocol, rate,
            midpoint_time-load_origin)
        started = time.perf_counter()
        candidate, audit = cycle_runner(
            context, original, original.eta.copy(), midpoint_drive,
            I3Controls(mura_enabled=True, front_enabled=False,
                       trial_dt_s=selected, front_dt_s=selected,
                       mura_transport_operator="compatible_dealiased"))
        accepted = float(audit["mura"]["accepted_dt_s"])
        tolerance = 64*np.finfo(float).eps*max(selected, 1e-300)
        attempts.append({
            "attempt": retry+1,
            "requested_duration_s": selected,
            "accepted_duration_s": accepted,
            "midpoint_physical_time_s": midpoint_time,
            "candidate_published": False,
            "wall_seconds": time.perf_counter()-started,
        })
        if accepted <= 0.0 or accepted > selected+tolerance:
            raise RuntimeError("invalid accepted physical substep")
        if accepted < selected-tolerance:
            selected = accepted
            continue
        # This candidate was generated by the midpoint of its accepted clock.
        accepted = selected
        attempts[-1]["candidate_published"] = True
        t0 = physical_time; t1 = t0+accepted
        initial_drive = driving(
            grid, initial_tensor_shear, protocol, rate, t0-load_origin)
        endpoint_drive = driving(
            grid, initial_tensor_shear, protocol, rate, t1-load_origin)
        before = energy_evaluator(context, original, initial_drive)
        mid_before = energy_evaluator(context, original, midpoint_drive)
        mid_after = energy_evaluator(context, candidate, midpoint_drive)
        after = energy_evaluator(context, candidate, endpoint_drive)
        work = ((mid_before.recoverable_elastic_J
                 -before.recoverable_elastic_J)
                +(after.recoverable_elastic_J
                  -mid_after.recoverable_elastic_J))
        delta_internal = after.internal_J-before.internal_J
        residual = delta_internal-work
        absolute_tolerance_J = 1e-26
        relative_tolerance = 1e-9
        incremental_scale = max(
            abs(delta_internal), abs(work), absolute_tolerance_J)
        balance_passed = bool(
            abs(residual) <= absolute_tolerance_J
            +relative_tolerance*incremental_scale)
        if not balance_passed:
            raise RuntimeError(
                "independent driver first-law check rejected segment: "
                f"residual={residual}, scale={incremental_scale}")
        return {
            "candidate": candidate, "audit": audit,
            "accepted_duration_s": accepted,
            "initial_drive": initial_drive,
            "midpoint_drive": midpoint_drive,
            "endpoint_drive": endpoint_drive,
            "before_energy": before, "after_energy": after,
            "external_work_J": work,
            "delta_internal_energy_J": delta_internal,
            "first_law_residual_J": residual,
            "first_law_incremental_scale_J": incremental_scale,
            "first_law_absolute_tolerance_J": absolute_tolerance_J,
            "first_law_relative_tolerance": relative_tolerance,
            "first_law_passed": balance_passed,
            "duration_selection_attempts": attempts,
            "discarded_shortened_candidates": retry,
        }
    raise RuntimeError("midpoint/duration selection exceeded retry limit")


def configure_restart_protocol(metadata, *, grid, macro_dt_s, protocol,
                               strain_rate_s, initial_tensor_shear,
                               protocol_transition, restart_checkpoint):
    """Resolve an exact restart or a declared no-jump protocol transition."""
    structural = {
        "grid": int(grid), "macro_dt_s": float(macro_dt_s),
    }
    mismatch = {key: (metadata.get(key), value)
                for key, value in structural.items()
                if metadata.get(key) != value}
    if mismatch:
        raise ValueError(f"restart structural mismatch: {mismatch}")
    if not protocol_transition:
        resolved_initial = (float(metadata["initial_tensor_shear"])
                            if initial_tensor_shear is None
                            else float(initial_tensor_shear))
        required = {
            "protocol": protocol, "strain_rate_s": float(strain_rate_s),
            "initial_tensor_shear": resolved_initial,
        }
        mismatch = {key: (metadata.get(key), value)
                    for key, value in required.items()
                    if metadata.get(key) != value}
        if mismatch:
            raise ValueError(
                f"restart protocol/configuration mismatch: {mismatch}")
        return {
            "initial_tensor_shear": resolved_initial,
            "load_origin_time_s": float(metadata["load_origin_time_s"]),
            "completed_intervals": int(metadata["completed_intervals"]),
            "records": list(metadata["records"]),
            "protocol_transitions": list(
                metadata.get("protocol_transitions", [])),
            "restart_mode": "EXACT_RESTART",
        }

    records = list(metadata.get("records", []))
    if not records:
        raise ValueError("protocol transition requires a recorded endpoint load")
    endpoint = records[-1].get("endpoint_load", {})
    mean = np.asarray(endpoint.get("mean_strain"), dtype=float)
    if mean.shape != (2, 2) or not np.all(np.isfinite(mean)):
        raise ValueError("protocol transition lacks the full endpoint mean strain")
    if not np.allclose(mean, mean.T, rtol=0.0, atol=2e-15):
        raise ValueError("protocol transition endpoint strain is not symmetric")
    if max(abs(mean[0, 0]), abs(mean[1, 1])) > 2e-15:
        raise ValueError("driver cannot preserve a non-shear endpoint load")
    endpoint_shear = .5*(float(mean[0, 1])+float(mean[1, 0]))
    if (initial_tensor_shear is not None
            and not np.isclose(float(initial_tensor_shear), endpoint_shear,
                               rtol=0.0, atol=2e-15)):
        raise ValueError(
            "declared transition initial shear differs from checkpoint endpoint")
    if not endpoint.get("fixed_eigenstrain_present", False):
        raise ValueError("transition cannot discard the checkpoint load owner")
    physical_time = float(metadata["physical_time_s"])
    transitions = list(metadata.get("protocol_transitions", []))
    transitions.append({
        "classification": "DECLARED_NO_LOAD_JUMP_PROTOCOL_TRANSITION",
        "parent_checkpoint": str(Path(restart_checkpoint).resolve()),
        "physical_time_s": physical_time,
        "inherited_completed_intervals": int(metadata["completed_intervals"]),
        "from_protocol": metadata["protocol"],
        "from_strain_rate_s": float(metadata["strain_rate_s"]),
        "to_protocol": protocol,
        "to_strain_rate_s": float(strain_rate_s),
        "endpoint_mean_strain": mean.tolist(),
        "intentional_load_jump": False,
    })
    return {
        "initial_tensor_shear": endpoint_shear,
        "load_origin_time_s": physical_time,
        "completed_intervals": 0,
        "records": [],
        "protocol_transitions": transitions,
        "restart_mode": "DECLARED_PROTOCOL_TRANSITION",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--initial-checkpoint", type=Path)
    parser.add_argument("--restart", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--grid", type=int, default=128)
    parser.add_argument("--intervals", type=int, required=True)
    parser.add_argument("--dt-s", type=float, default=4.8828125e-7)
    parser.add_argument("--protocol", choices=("hold", "continued_deformation"),
                        required=True)
    parser.add_argument("--strain-rate-s", type=float, default=100.0)
    parser.add_argument("--initial-tensor-shear", type=float)
    parser.add_argument("--protocol-transition", action="store_true",
                        help="start a no-load-jump protocol at a restart endpoint")
    args = parser.parse_args()
    if (args.initial_checkpoint is None) == (args.restart is None):
        raise ValueError("select exactly one initial checkpoint or restart")
    output = args.output_dir; output.mkdir(parents=True, exist_ok=True)
    context = resolved_bicrystal(
        grid=args.grid, length_m=3.2e-6, interface_width_m=4e-7,
        temperature_K=1100.0, child_line_fraction=.35)
    rate = 0.0 if args.protocol == "hold" else float(args.strain_rate_s)
    if args.restart is None:
        if args.protocol_transition:
            raise ValueError("protocol transition requires --restart")
        initial_tensor_shear = (.01 if args.initial_tensor_shear is None
                                else float(args.initial_tensor_shear))
        state, source_metadata = load_stage(args.initial_checkpoint, context)
        physical_time = float(source_metadata.get("physical_time_s", 0.0))
        load_origin = physical_time
        completed = 0; records = []
        cumulative_work = 0.0
        d0 = driving(args.grid, initial_tensor_shear,
                     args.protocol, rate, 0.0)
        initial_internal = energy(context, state, d0).internal_J
        source_checkpoint = args.initial_checkpoint.resolve()
        protocol_transitions = []
        restart_mode = "FRESH_PROTOCOL_FROM_INITIAL_CHECKPOINT"
    else:
        state, metadata = load_stage(args.restart, context)
        configuration = configure_restart_protocol(
            metadata, grid=args.grid, macro_dt_s=args.dt_s,
            protocol=args.protocol, strain_rate_s=rate,
            initial_tensor_shear=args.initial_tensor_shear,
            protocol_transition=args.protocol_transition,
            restart_checkpoint=args.restart)
        initial_tensor_shear = configuration["initial_tensor_shear"]
        physical_time = float(metadata["physical_time_s"])
        load_origin = configuration["load_origin_time_s"]
        completed = configuration["completed_intervals"]
        records = configuration["records"]
        protocol_transitions = configuration["protocol_transitions"]
        restart_mode = configuration["restart_mode"]
        cumulative_work = float(metadata["cumulative_external_work_J"])
        initial_internal = float(metadata["initial_internal_energy_J"])
        source_checkpoint = Path(metadata["source_checkpoint"])
    started = time.perf_counter()
    for interval in range(completed, args.intervals):
        remaining = float(args.dt_s); segments = []
        while remaining > 64*np.finfo(float).eps*args.dt_s:
            t0 = physical_time; requested = remaining
            segment_started = time.perf_counter()
            transaction = advance_consistent_midpoint_segment(
                context, state, grid=args.grid,
                initial_tensor_shear=initial_tensor_shear,
                protocol=args.protocol, rate=rate, physical_time=t0,
                load_origin=load_origin, requested_duration=requested)
            candidate = transaction["candidate"]
            audit = transaction["audit"]
            accepted = transaction["accepted_duration_s"]
            after = transaction["after_energy"]
            work = transaction["external_work_J"]
            cumulative_work += work
            physical_time = t0+accepted; remaining -= accepted; state = candidate
            segments.append({
                "requested_duration_s": requested,
                "accepted_duration_s": accepted,
                "physical_time_start_s": t0,
                "physical_time_end_s": physical_time,
                "external_work_J": work,
                "delta_internal_energy_J": transaction[
                    "delta_internal_energy_J"],
                "first_law_residual_J": transaction["first_law_residual_J"],
                "first_law_incremental_scale_J": transaction[
                    "first_law_incremental_scale_J"],
                "first_law_absolute_tolerance_J": transaction[
                    "first_law_absolute_tolerance_J"],
                "first_law_relative_tolerance": transaction[
                    "first_law_relative_tolerance"],
                "first_law_passed": transaction["first_law_passed"],
                "duration_selection_attempts": transaction[
                    "duration_selection_attempts"],
                "discarded_shortened_candidates": transaction[
                    "discarded_shortened_candidates"],
                "ordering_linear_iterations": audit["mura"].get(
                    "ordering_linear_iterations"),
                "ordering_internal_substeps": audit["mura"].get(
                    "ordering_internal_substeps"),
                "wall_seconds": time.perf_counter()-segment_started,
            })
        endpoint_drive = driving(
            args.grid, initial_tensor_shear, args.protocol, rate,
            physical_time-load_origin)
        endpoint_energy = energy(context, state, endpoint_drive)
        records.append({
            "interval": interval+1,
            "physical_time_end_s": physical_time,
            "load_elapsed_time_s": physical_time-load_origin,
            "endpoint_load": load_record(endpoint_drive),
            "endpoint_observables": observables(context, state, endpoint_drive),
            "endpoint_energy": asdict(endpoint_energy),
            "segments": segments,
            "cumulative_external_work_J": cumulative_work,
            "cumulative_internal_energy_change_J": (
                endpoint_energy.internal_J-initial_internal),
            "cumulative_first_law_residual_J": (
                endpoint_energy.internal_J-initial_internal-cumulative_work),
        })
        checkpoint = output/f"checkpoint_{interval+1:06d}.npz"
        metadata = {
            "stage": "V49_COMPLETE_INTERVAL", "grid": args.grid,
            "macro_dt_s": args.dt_s, "completed_intervals": interval+1,
            "physical_time_s": physical_time,
            "load_origin_time_s": load_origin,
            "initial_tensor_shear": initial_tensor_shear,
            "protocol": args.protocol, "strain_rate_s": rate,
            "restart_mode": restart_mode,
            "protocol_transitions": protocol_transitions,
            "source_checkpoint": str(source_checkpoint), "records": records,
            "cumulative_external_work_J": cumulative_work,
            "initial_internal_energy_J": initial_internal,
        }
        save_stage(checkpoint, state, context, metadata)
        manifest = {
            "schema": "asb-drx/v49/physical-continuation/v1",
            "generated_utc": datetime.now(timezone.utc).isoformat(),
            "source_sha": subprocess.check_output(
                ["git", "rev-parse", "HEAD"], text=True).strip(),
            "status": "RUNNING" if interval+1 < args.intervals else "COMPLETE",
            **metadata, "latest_checkpoint": str(checkpoint.resolve()),
            "latest_checkpoint_sha256": digest(checkpoint),
            "source_checkpoint_sha256": digest(source_checkpoint),
            "wall_seconds": time.perf_counter()-started,
        }
        atomic_json(output/"run_manifest.json", manifest)
    print(json.dumps({key: manifest[key] for key in (
        "status", "completed_intervals", "physical_time_s",
        "latest_checkpoint_sha256", "wall_seconds")}, sort_keys=True))


if __name__ == "__main__":
    main()
